### ISSUE TITLE
Pretrained model in ckp_A

### ISSUE THREAD

**Issue by xiangdonglai** [MengZephyr/DynamicNeuralGarments#1]
Dear author,

Thank you for this great work. Following your instruction, I am able to get the network training started. However, I noticed in this line [here](https://github.com/MengZephyr/DynamicNeuralGarments/blob/main/GarmentMotionRenderer/Train.py#L54) that the network is fine-tuned from a pre-trained model in ckp_A. I am wondering what that pretrained model is and how it influences the final output. In addition, are you interested in releasing that model so that we can exactly reproduce the same results?

Thanks again.

**Comment by MengZephyr** [comment]
It’s just a temporary ckp.
